import * as Haptics from "expo-haptics";
import { useMemo } from "react";
import { ActivityIndicator, FlatList, Platform, Pressable, StyleSheet, Text, View } from "react-native";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useBakalariAbsence } from "@/hooks/use-bakalari-data";
import type { AbsenceSubject } from "@/shared/bakalari-data";

function ping() { if (Platform.OS !== "web") void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); }

export default function AbsenceScreen() {
  const colors = useColors(); const { data, loading, refreshing, error, cacheAge, fromCache, refresh } = useBakalariAbsence(); const subjects = useMemo(() => data?.subjects ?? [], [data?.subjects]);
  const emptyState = loading ? <View className="items-center rounded-2xl bg-surface p-6"><ActivityIndicator color={colors.primary} /><Text className="mt-3 text-sm text-muted">Načítám absenci…</Text></View> : error ? <View className="rounded-2xl bg-surface p-5"><Text className="text-sm font-bold text-foreground">Absenci se nepodařilo načíst</Text><Text className="mt-2 text-xs leading-5 text-muted">{error}</Text><Pressable onPress={() => { ping(); refresh(); }} style={styles.retry}><Text className="text-sm font-bold text-primary">Zkusit znovu</Text><IconSymbol name="arrow.clockwise" size={16} color={colors.primary} /></Pressable></View> : <View className="items-center rounded-2xl bg-surface p-6"><IconSymbol name="info.circle" size={30} color={colors.primary} /><Text className="mt-3 text-base font-bold text-foreground">Žádná data absence</Text><Text className="mt-1 text-center text-sm text-muted">Škola neposkytla přehled absence.</Text></View>;
  const renderSubject = ({ item }: { item: AbsenceSubject }) => <View className="mb-3 rounded-2xl bg-surface p-4" style={styles.card}><View className="flex-row items-center justify-between"><Text className="flex-1 text-base font-bold text-foreground">{item.subject}</Text><Text className="text-sm font-bold" style={{ color: item.percent >= (data?.thresholdPercent ?? 18) ? colors.error : colors.primary }}>{item.percent.toFixed(1).replace(".", ",")} %</Text></View><View className="mt-3 h-2 overflow-hidden rounded-full" style={{ backgroundColor: colors.border }}><View className="h-2 rounded-full" style={{ width: `${Math.min(100, item.percent)}%`, backgroundColor: item.percent >= (data?.thresholdPercent ?? 18) ? colors.error : colors.primary }} /></View><Text className="mt-2 text-xs text-muted">{item.absence} zameškaných z {item.lessons} hodin · pozdě {item.late}</Text></View>;
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><FlatList data={subjects} keyExtractor={(item) => item.id} renderItem={renderSubject} refreshing={refreshing} onRefresh={() => { ping(); refresh(); }} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} ListHeaderComponent={<View><View className="flex-row items-center justify-between pt-3"><View><Text className="text-sm font-semibold text-primary">Docházka školy</Text><Text className="mt-1 text-3xl font-bold text-foreground">Absence</Text></View><Pressable onPress={() => { ping(); refresh(); }} style={styles.iconButton}><IconSymbol name="arrow.clockwise" size={20} color={colors.primary} /></Pressable></View><Text className="mt-1 text-sm text-muted">Přehled zameškaných hodin podle předmětů.</Text>{fromCache ? <Text className="mt-1 text-xs font-semibold text-warning">Offline cache · {cacheAge ?? "uloženo"}</Text> : null}<View className="mt-6 flex-row gap-2"><View className="flex-1 rounded-2xl bg-surface p-4" style={styles.card}><Text className="text-xs font-semibold text-muted">Zameškané</Text><Text className="mt-1 text-2xl font-bold text-foreground">{loading ? "…" : data?.totals.missed ?? 0}</Text><Text className="mt-1 text-xs text-muted">hodin</Text></View><View className="flex-1 rounded-2xl bg-surface p-4" style={styles.card}><Text className="text-xs font-semibold text-muted">Pozdě</Text><Text className="mt-1 text-2xl font-bold text-foreground">{loading ? "…" : data?.totals.late ?? 0}</Text><Text className="mt-1 text-xs text-muted">příchodů</Text></View></View><View className="mb-4 mt-7 flex-row items-center justify-between"><Text className="text-xl font-bold text-foreground">Předměty</Text><Text className="text-xs font-semibold text-muted">{subjects.length} celkem</Text></View></View>} ListEmptyComponent={emptyState} ListFooterComponent={subjects.length ? <Text className="mb-5 mt-2 text-center text-xs leading-5 text-muted">Červené hodnoty překračují doporučený limit školy.</Text> : null} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingBottom: 24 }, card: { shadowColor: "#172033", shadowOpacity: 0.05, shadowRadius: 10, shadowOffset: { width: 0, height: 3 }, elevation: 1 }, iconButton: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#E5EEFF", alignItems: "center", justifyContent: "center" }, retry: { marginTop: 14, borderTopWidth: 1, borderTopColor: "#E5EAF2", paddingTop: 13, flexDirection: "row", alignItems: "center", justifyContent: "space-between" } });
